---
- name: Wait for connection and run tasks on Windows laptops
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for the connection to be available and run tasks
      ansible.builtin.include_tasks: wait_and_run_tasks.yml
      loop: "{{ ansible_play_hosts }}"
      loop_control:
        loop_var: target_host
      vars:
        target_host: "{{ target_host }}"
