---
- name: Configure hosts file for YouTube restricted mode
  hosts: ninjas
  tasks:
    - name: Backing up current hosts file
      win_copy:
        src: C:\Windows\System32\drivers\etc\hosts
        dest: C:\Windows\System32\drivers\etc\hosts.bak
        remote_src: yes

    - name: Setting restricted mode for www.youtube.com
      win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "216.239.38.120 www.youtube.com"
        create: yes

    - name: Setting restricted mode for m.youtube.com
      win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "216.239.38.120 m.youtube.com"
        create: yes

    - name: Setting restricted mode for youtubei.googleapis.com
      win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "216.239.38.120 youtubei.googleapis.com"
        create: yes

    - name: Setting restricted mode for youtube.googleapis.com
      win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "216.239.38.120 youtube.googleapis.com"
        create: yes

    - name: Setting restricted mode for www.youtube-nocookie.com
      win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "216.239.38.120 www.youtube-nocookie.com"
        create: yes
